#This is a fake code to provide typing hint

from PySide6.QtWidgets import QApplication, QDialog, QMainWindow, QSystemTrayIcon
from PySide6.QtCore import QTimer
from logic.main import UILogic
from libs.ui.setting import Ui_Settings
from threading import Thread

class LogicFrame:
    def __init__(self, file=None):
        self.app = ... #type: QApplication
        self.MainWindow = ... #type: QMainWindow
        self.ui = ... #type: UILogic
        self.tray = ... #type: QSystemTrayIcon
        self.setting = ... #type: QDialog
        self.setting_ui = ... #type: Ui_Settings
        self.tool_thread = ... #type: Thread
        self.online = False
        self.running = True
        self.auto_save_timer = ... #type: QTimer
    def ticker(self, func, interval): ...
    def check_running(self): ...
    def tray_activated(self, reason): ...
    def accept(self): ...
    def setting_show(self): ...
    def show_tools(self): ...
    def command_online(self): ...
    def retrans(self, lang=None): ...
    def auto_translate(self): ...
    def start_tool(self): ...
    def exec(self): ...
    def close(self, evt): ...
