from PySide6.QtWidgets import QDialog, QMenu, QMainWindow, QSystemTrayIcon
from PySide6.QtCore import QTimer, QEvent
from logic.main import LMain

class LMainWindow(QMainWindow):
    def __init__(self, file=None):
        super().__init__()
        #Window Build
        self.ui = ... # type: LMain
        self.tray = ... # type: QSystemTrayIcon
        self.tmenu = ... # type: QMenu
        self.setting = ... # type: QDialog
        self.online = False
        self.running = True
        self.argv = file
        self.auto_save_timer = ... # type: QTimer

    def connect_actions(self): ...
    def ticker(self, func, interval): ...
    def check_running(self): ...
    def tray_activated(self, reason): ...
    def accept(self): ...
    def setting_show(self): ...
    def show_tools(self): ...
    def command_online(self): ...
    def retrans(self, lang=None): ...
    def auto_translate(self): ...
    def closeEvent(self, evt:QEvent): ...
